#ifndef MEMORIES_PC_MODS_EXPORTS_H
#define MEMORIES_PC_MODS_EXPORTS_H
/* The names a code mod may bind to, and where each one is. The table is
 * generated by tools/pc/build_game32.py (mod_exports.c beside stubs.c): every
 * global the game units and the port define, every guest variable pinned to
 * its retail address, and the aliases the link resolves. The linker fills in
 * the addresses, so it is the same table on Linux and on Windows. Sorted by
 * name (strcmp), without repeats. */

typedef struct {
    const char *name;
    void *address;
} MemoriesModExport;

extern const MemoriesModExport Memories_ModExports[];
extern const unsigned Memories_ModExportCount;

/* A name from the short list of C library functions the host lends mods
 * (mod_libc.c), else from the table above; NULL when neither has it. The
 * C library comes first, so a standard name always means the standard
 * function. */
void *Mods_Lookup(const char *name);

/* The C library list alone (mod_libc.c), and whether it is in order. */
void (*Mods_LibcLookup(const char *name))(void);
int Mods_LibcSorted(void);

/* MEMORIES_MOD_EXPORTS=1: print the table ("address name" per line) and
 * exit, so tools/pc/check_mod_exports.py can hold it against the link. */
int Mods_PrintExports(void);

#endif
