#!/usr/bin/env python3
"""Embed the PNG unchanged so native executables do not depend on asset paths."""
from pathlib import Path
root = Path(__file__).resolve().parents[2]
source = root / "src/pc/assets/ps1-controller.png"
data = source.read_bytes()
out = root / "src/pc/assets/ps1_controller_png.h"
with out.open("w") as f:
    f.write("/* Generated by tools/pc/embed_controls_art.py. Do not edit. */\n")
    f.write("static const unsigned char ps1_controller_png[] = {\n")
    for i in range(0, len(data), 24):
        f.write("    " + ",".join(str(b) for b in data[i:i+24]) + ",\n")
    f.write("};\n")
print(f"Embedded {len(data)} bytes unchanged from {source.relative_to(root)}")
